### ISSUE TITLE
Python版でKokkos::initializeを自動呼び出し

### ISSUE THREAD

**Issue by KowerKoint** [qulacs/scaluq#115]
binding.cppに以下を書けばimport時とモジュールを閉じたときに自動でinitialize/finalizeを読んでくれるらしい。
InitializationSettingsの内容は環境変数で渡せるので大丈夫。

```cpp
    m.add_object("_cleanup", py::capsule([]() { Kokkos::finalize(); }));

    Kokkos::initialize();
```

**Comment by KowerKoint** [comment]
↑はPybind11の書き方

**Comment by gandalfr-KY** [comment]
https://github.com/qulacs/scaluq/pull/116
