### ISSUE TITLE
getter/setterの命名

### ISSUE THREAD

**Issue by KowerKoint** [qulacs/scaluq#145]
`PauliOperator::get_coef`、`internal::XGateImpl::target`など、getterにはメンバの名前に`get_`がついているものとついていないものがある。
また、`StateVector::amplitudes`のようにgetterに見えて実際はタダのメンバ取得ではなく大きなコピーがかかっているものもある。
これらをわかりやすくなるために、以下の命名規則を採用する。

- メンバに直接アクセスする場合、または実際にはmaskなど他の持ち方をしているがそこからの変換コストが低くメンバとして直接持っているかのように振る舞いたい場合
  - メンバと同じ名前の関数
  - 返り値はプリミティブ型や`Complex`のように十分コピーコストが小さければ`T`、vectorのように大きければ`const T&`で返す
  - 可変にしたい場合、同名の非const関数でsetterを定義する。返り値は`T&`。もし本当はその形で持っていないなら`internal::BitVector::_Reference`のように参照型のように振る舞うラッパークラスを返してもよいが、現状そういうものはなさそう。
- 計算して結果を返す場合
  - `get_`つきまたはその他の適切な動詞型の名前をつける。
  - `get_target_qubit_list`、`get_target_qubit_mask`に関してはどうするべきか要検討(これは統一して両方getでもいいかも？)

**Comment by gandalfr-KY** [comment]
> get_target_qubit_list、get_target_qubit_maskに関してはどうするべきか要検討(これは統一して両方getでもいいかも？)

これはまさに「メンバに直接アクセスする場合、または実際にはmaskなど他の持ち方をしているがそこからの変換コストが低くメンバとして直接持っているかのように振る舞いたい場合」ではないですか？これに照らせばgetを付けない名前がよいのではないでしょうか。

**Comment by gandalfr-KY** [comment]
https://github.com/qulacs/scaluq/pull/161

**Comment by KowerKoint** [comment]
> これに照らせばgetを付けない名前がよいのではないでしょうか。

ゲートによっては(Probablisticとか)取得が難しいというイメージだったけど、　だいたい一瞬だしProbablisticも今例外で今後コンストラクタでマスク作るくらいでいい気もするのでgetつけなくていいかも
