### ISSUE TITLE
StateVectorBatch

### ISSUE THREAD

**Issue by KowerKoint** [qulacs/scaluq#91]
複数の状態ベクトルを持つクラス
単にStateVectorの配列を持つより、1つのクラスにしたほうが効率が良さそうなので作る
中身は2次元Viewにするのか1次元に並べるのか、データ方向はどっちがいいのか考える
おそらく1次元Viewで0番目の状態ベクトル, 1番目の状態ベクトル, …と並べるのが一番良いのでそれで実装を始める？

**Comment by gandalfr-KY** [comment]
https://github.com/qulacs/scaluq/pull/109
